# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Speakably' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'iOSDropDown'
  pod 'BATabBarController', '~> 2.0.0'
  pod 'CalendarKit'
  pod 'NavigationDropdownMenu', '~> 5.0.0'
  pod 'FoldingCell'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  # Pods for Speakably

  target 'SpeakablyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpeakablyUITests' do
    # Pods for testing
  end

end
